"""
QR service — generates static, HMAC-signed QR codes for classrooms
and verifies scanned QR payloads.
"""

from __future__ import annotations

import hmac
import hashlib
import json

from config import QR_HMAC_SECRET


def generate_static_qr(classroom_id: str) -> dict:
    """
    Create a static QR payload for a classroom.  The QR data contains
    only the classroom_id and an HMAC signature to prove authenticity.
    This QR never expires — it can be printed and posted in the room.
    """
    # HMAC-SHA256 over classroom_id
    hmac_signature = hmac.new(
        QR_HMAC_SECRET.encode("utf-8"),
        classroom_id.encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()

    qr_payload = {
        "classroom_id": classroom_id,
        "hmac_signature": hmac_signature,
    }

    return {
        "classroom_id": classroom_id,
        "hmac_signature": hmac_signature,
        "qr_data": json.dumps(qr_payload),
    }


def verify_qr_signature(classroom_id: str, hmac_signature: str) -> bool:
    """
    Verify that a scanned QR payload has a valid HMAC signature,
    proving it was generated by an authorised admin.
    """
    expected = hmac.new(
        QR_HMAC_SECRET.encode("utf-8"),
        classroom_id.encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()

    return hmac.compare_digest(expected, hmac_signature)
